GET http://localhost:8080/api/users

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "test@email.com"
}

###

GET http://localhost:8080/api/chirps

###

GET http://localhost:8080/api/chirps/39ba1a9a-2313-418f-b3cc-6481f6fa901a

###

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "Chirpy is awesome",
  "user_id": "34e3148a-18c0-4d1d-b383-a3b44ba2c94a"
}

###

POST http://localhost:8080/admin/reset
Content-Type: application/json