GET http://localhost:8080/api/users

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "test@email.com"
}

###

POST http://localhost:8080/admin/reset
Content-Type: application/json